spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paycaldb?serverTimezone=UTC&targetServerType=master
    username: postgres
    password: password
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
  jpa.hibernate.ddl-auto: validate
  jpa.database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  jpa.hibernate.naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  flyway:
    baseline-on-migrate: true
    enabled: true
    table: "schema_version"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

